apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2019-08-04T13:37:25Z
  generation: 1
  labels:
    app: ocr-app-deployment
  name: ocr-app-deployment
  namespace: default
  resourceVersion: "39048"
  selfLink: /apis/apps/v1/namespaces/default/deployments/ocr-app-deployment
  uid: fedb4f0e-b6bc-11e9-b8e2-42010a840077
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ocr-app-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ocr-app-deployment
    spec:
      containers:
      - image: gcr.io/slb-it-op-es-analytics-dev/ocr-app:0.3
        imagePullPolicy: IfNotPresent
        name: ocr-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-08-04T13:37:26Z
    lastUpdateTime: 2019-08-04T13:37:26Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
